language: ruby
rvm:
- 2.3.3

install:
  - bundle install
  - gem install html-proofer
  - pip install awscli
script: 
  - bundle exec jekyll build 
  - htmlproofer ./_site --disable-external

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
